PhotoAlbum/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PhotoAlbum.Models;
using System.Net.Http;
using PhotoAlbum.DAL;
using Microsoft.AspNet.Identity;
using PhotoAlbum.Filters;

namespace PhotoAlbum.Controllers
{
    [Authorize]
    public class AlbumsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private CommentsCRUD commentsRepo = new CommentsCRUD();

        [HttpGet]
        public ActionResult GetComments(int albumId)
        {
            return PartialView("_CommentsPartial", commentsRepo.GetAllComments(albumId));
        }

        [HttpDelete]
        [Authorize]
        public void DeleteComment(int id)
        {
            commentsRepo.DeleteComment(id);
            commentsRepo.SaveChanges();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult WriteComment(string commentHtml, int albumId)
        {
            if (string.IsNullOrEmpty(commentHtml) || string.IsNullOrWhiteSpace(commentHtml))
            {
                return null;
            }

            var comment = commentsRepo.CreateComment(commentHtml, albumId, User.Identity.GetUserId());
            commentsRepo.SaveChanges();

            return PartialView("_CommentsPartial", new List<CommentView>
            {
                new CommentView
                {
                    CommentId = comment.Id,
                    Comment = comment.CommentText,
                    DateTime = comment.DateTime,
                    UserName = User.Identity.GetUserName()
                }
            });
        }

        [HttpGet]
        public ActionResult GetComment(int commentId)
        {
            return PartialView("_CommentsPartial",
                new List<CommentView> { commentsRepo.GetComment(commentId) });
        }



        public ActionResult Slideshow(int albumId)
        {
            var album = db.Albums.Include(a => a.Photos).Single(a => a.Id == albumId);

            ViewBag.photoUrls = new List<String>();
            foreach (var photo in album.Photos)
            {
                ViewBag.photoUrls.Add($"/Photo/{ photo.Guid }");
            }
            ViewBag.timeout = 2000;
            ViewBag.transition = 400;

            return View();
        }

        [HttpPost]
        public void ReplaceImage(string aviaryUrl, int id)
        {
            var photo = db.Photos.Find(id);
            using (var client = new WebClient())
            {
                photo.Image = client.DownloadData(new Uri(aviaryUrl));
                db.SaveChanges();
            }
        }

        // GET: Albums
        [AllowAnonymous]
        public async Task<ActionResult> Index()
        {
            var albums = new List<AlbumIndexViewModel>();
            foreach (var album in db.Albums.Include(a => a.User).ToArray())
            {
                albums.Add(new AlbumIndexViewModel
                {
                    Album = album,
                    Rating = db.Ratings.Where(r => r.AlbumId == album.Id).Average(r => (double?)r.Rate)
                });
            }

            return View(albums);
        }

        // GET: Albums/Details/5
        [AllowAnonymous]
        [Mobile]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = await db.Albums.FindAsync(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            var AlbumView = new AlbumViewModel
            {
                Album = album,
                Photos = album.Photos,
            };

            return View(AlbumView);
        }

        [AllowAnonymous]
        public async Task<ActionResult> Mobile(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = await db.Albums.FindAsync(id);
            if (album == null)
            {
                return HttpNotFound();
            }

            return View(album);
        }

        // GET: Albums/Create
        public ActionResult Create()
        {
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Albums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,AlbumName,IsPrivate,ApplicationUserId")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Albums.Add(album);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Email", album.ApplicationUserId);
            return View(album);
        }

        // GET: Albums/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = await db.Albums.FindAsync(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Email", album.ApplicationUserId);
            return View(album);
        }

        // POST: Albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,AlbumName,IsPrivate,ApplicationUserId")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Entry(album).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Email", album.ApplicationUserId);
            return View(album);
        }

        // GET: Albums/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = await db.Albums.FindAsync(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Album album = await db.Albums.FindAsync(id);
            db.Albums.Remove(album);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
                commentsRepo.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PhotoAlbum/Controllers/PhotoController.cs
using Microsoft.AspNet.Identity;
using PhotoAlbum.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using static System.Net.Mime.MediaTypeNames;

namespace PhotoAlbum.Controllers
{
    public class PhotoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [HttpDelete]
        public ActionResult DeletePhoto(int photoId)
        {
            var photo = db.Photos.Find(photoId);
            if (photo == null)
            {
                return Json(new { Message = "Fail" });
            }
            db.Photos.Remove(photo);
            db.SaveChanges();

            return Json(new { Message = "Success" });
        }
        
        [HttpPost]
        public ActionResult SaveUploaded(int albumId)
        {
            if (db.Albums.Find(albumId).ApplicationUserId != User.Identity.GetUserId())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            bool isSavedSuccessfully = true;
            string fName = "";

            try
            {
                HttpPostedFileBase file = Request.Files["file"];
                fName = file.FileName;

                if (file.ContentLength > 0)
                {
                    byte[] imageData = null;
                    using (var binaryReader = new BinaryReader(file.InputStream))
                    {
                        imageData = binaryReader.ReadBytes(file.ContentLength);
                    }

                    var parts = file.FileName.Split('.');
                    var format = "." + parts.Last();
                    var name = file.FileName.Replace(format, "");

                    var photo = new Photo()
                    {
                        Name = name,
                        Format = format,
                        Image = imageData,
                        AlbumId = albumId,
                    };

                    db.Photos.Add(photo);
                    db.SaveChanges();
                }
            }
            catch (Exception)
            {
                isSavedSuccessfully = false;
            }

            if (isSavedSuccessfully)
            {
                return Json(new { Message = fName });
            }
            else
            {
                return Json(new { Message = "Error in saving file" });
            }
        }

        [HttpGet]
        public ActionResult GetByReference(Guid guid)
        {
            var imageData = new MemoryStream(db.Photos.FirstOrDefault(x => x.Guid == guid).Image);

            return new FileStreamResult(imageData, "image/jpeg");
        }

        // GET: Photo
        public ActionResult Index()
        {
            return View();
        }

        // GET: Photo/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Photo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Photo/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Photo/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Photo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Photo/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Photo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PhotoAlbum/Views/Albums/Create.cshtml
@model PhotoAlbum.Models.Album

@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h2>Create</h2>


            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Album</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.AlbumName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.AlbumName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.AlbumName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.IsPrivate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsPrivate)
                                @Html.ValidationMessageFor(model => model.IsPrivate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ApplicationUserId, "ApplicationUserId", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("ApplicationUserId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
</div>

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }

PhotoAlbum/Views/Albums/Delete.cshtml
@model PhotoAlbum.Models.Album

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h2>Delete</h2>

            <h3>Are you sure you want to delete this?</h3>
            <div>
                <h4>Album</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.User.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.User.Email)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.AlbumName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.AlbumName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IsPrivate)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsPrivate)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                }
            </div>
        </div>
    </div>
</div>

PhotoAlbum/Views/Albums/Details.cshtml
@model PhotoAlbum.Models.AlbumViewModel
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <div class="row">
        <div class="col-md-5 col-md-offset-1 column-vcenter">
            <h2>Details</h2>

            <div>
                <h4>Album</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Album.User.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Album.User.Email)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Album.AlbumName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Album.AlbumName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Album.IsPrivate)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Album.IsPrivate)
                    </dd>

                </dl>
            </div>
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.Album.Id }) |
                @Html.ActionLink("Back to List", "Index") |
                @Html.ActionLink("Slideshow", "Slideshow", new { albumId = Model.Album.Id })
            </p>
            <hr />
        </div>

        <div class="col-md-5 text-center column-vcenter">
            <div id="rating_block" hidden>
                <h4>Rate album:</h4>
                <div class="ratebox" data-id="ratebox_1" style="margin: auto;"></div>
            </div>
            <div id="rating_spinner">
                <i class="fa fa-spinner fa-spin fa-5x fa-fw" style="color: mediumseagreen;"></i>
                <span class="sr-only">Loading rating...</span>
            </div>
        </div>
    </div>


    @{ int i = 0; }

    @foreach (var photo in Model.Photos)
    {
        var url = $"/Photo/{ photo.Guid }";
        var urlForAviary = string.Format("data:image;base64,{0}", Convert.ToBase64String(photo.Image));

        if (i % 3 == 0)
        {
            WriteLiteral("<div class=\"row\">");
        }
        <div class="@photo.Id">
            <div class="col-md-4">
                <div class="img-container img-rounded text-center">
                    <img style="width: 100%;" class="@photo.Id" id="@photo.Id" src="@url" data-toggle="modal" data-target="#modal_@i" />
                </div>
                <br />
            </div>

            <div id="modal_@i" class="modal fade text-center" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Image</h4>
                        </div>
                        <div class="modal-body">
                            <p><img class="@photo.Id" style="width:100%;max-width:600px;" src="@url" /></p>
                            <p><input type='image' id="imgInput" src='http://images.aviary.com/images/edit-photo.png' value='Edit photo' onclick="return launchEditor('@photo.Id', '@urlForAviary');" /></p>
                            <input type="submit" value="Delete" onclick="deletePhoto(@photo.Id);" />
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        if (i % 3 == 2)
        {
            WriteLiteral("</div>");
        }
        i++;

    }

    <div>
        @if (User.Identity.IsAuthenticated)
        {
            <div id="editor_block" hidden>
                <h4>Comment album:</h4>
                <div style="margin-bottom: 25px;">
                    <div id="comment_editor"></div>
                    @using (Ajax.BeginForm("WriteComment", "Albums",
                        new AjaxOptions { OnSuccess = "writeCommentSuccessCallback" }))
                    {
                        <input type="hidden" name="albumId" id="album_id" value="@Model.Album.Id" />
                        <input type="hidden" name="commentHtml" id="comment_html" value="" />
                        <button type="submit" id="send-comment" style="width: 150px;" class="btn btn-primary">Send</button>
                    }
                </div>
            </div>

            <div id="editor_spinner" class="text-center" style="margin: 25px;">
                <i class="fa fa-spinner fa-spin fa-5x fa-fw" style="color: mediumseagreen;"></i>
                <span class="sr-only">Loading editor...</span>
            </div>
        }

        <div id="comments"></div>

        <div id="comments_spinner" class="text-center" style="margin: 25px;">
            <i class="fa fa-spinner fa-spin fa-5x fa-fw" style="color: mediumseagreen;"></i>
            <span class="sr-only">Loading comments...</span>
        </div>
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/summernote.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.1.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/bootstrap-notify.min.js"></script>

    <script>
        var albumId = @Model.Album.Id;
        var userId = '@User.Identity.GetUserId()';
        var starSize = 30;
    </script>
    <script src="~/Scripts/errorHandling.js"></script>
    <script src="~/Scripts/pushNotifications.js"></script>
    <script src="~/Scripts/raterater.jquery.js"></script>
    <script src="~/Scripts/rating.js"></script>
    <script src="~/Scripts/desktop.js"></script>

    <!-- Aviary editor -->
    <script type="text/javascript" src="http://feather.aviary.com/imaging/v3/editor.js"></script>
    <script src="~/Scripts/aviary.js"></script>
}

@section css
{
    <link href="@Url.Content("~/Content/raterater.css")" rel="stylesheet" type="text/css">
    <link href="@Url.Content("~/Content/summernote.css")" rel="stylesheet" type="text/css">
    <link href="~/Content/animate.css" rel="stylesheet" type="text/css" />
}

PhotoAlbum/Views/Albums/Edit.cshtml
@model PhotoAlbum.Models.Album

@{
    ViewBag.Title = "Edit";
}

<link rel="stylesheet" href="~/Scripts/dropzone/basic.css" />
<link rel="stylesheet" href="~/Scripts/dropzone/dropzone.css" />

<style type="text/css">
    #dropzoneForm {
        background: white;
        border: black dashed 3px;
        padding: 50px;
        text-align: center;
        color: black;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h2>Edit</h2>


            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Album</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.AlbumName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.AlbumName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.AlbumName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.IsPrivate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsPrivate)
                                @Html.ValidationMessageFor(model => model.IsPrivate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ApplicationUserId, "ApplicationUserId", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("ApplicationUserId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>

            <div>
                <form action="@Url.Action("SaveUploaded","Photo", new { albumId = Model.Id})" method="post" enctype="multipart/form-data" class="dropzone" id="dropzoneForm" border none;">
                    <div class="fallback">
                        <input name="file" type="file" multiple />
                        <input type="submit" value="Upload" />
                    </div>
                </form>
                <br />
                <p><a id="clearbtn" class="btn btn-primary btn-lg">Clear</a></p>
            </div>
        </div>
    </div>
</div>

            <script src="~/Scripts/dropzone/dropzone.js"></script>
            <script type="text/javascript">
                Dropzone.options.dropzoneForm = {
                    maxFiles: 50,
                    // addRemoveLinks: true,
                    dictRemoveFile: 'Delete',
                    acceptedFiles: "image/*",
                    init: function () {
                        this.on("complete", function (data) {
                            var res = JSON.parse(data.xhr.responseText);
                        });

                        $('#clearbtn').click(function () {
                            $('div.dz-success').remove();
                            $('div.dz-error').remove();
                        });
                    }
                };
            </script>

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }

PhotoAlbum/Views/Albums/Index.cshtml
@model IEnumerable<PhotoAlbum.Models.AlbumIndexViewModel>

@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h2>Index</h2>

            <p>
                @Html.ActionLink("Create New", "Create")
            </p>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Album.User.Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Album.AlbumName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Album.IsPrivate)
                    </th>
                    <th>
                        Total rating
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Album.User.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Album.AlbumName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Album.IsPrivate)
                        </td>
                        @if (item.Rating.HasValue)
                        {
                            <td>
                                @string.Format(System.Globalization.CultureInfo.CreateSpecificCulture("en-US") ,"{0:0.00} ", item.Rating)
                                <div class="row">
                                    <div class="ratebox" data-id="@item.Album.Id" data-rating=@string.Format(System.Globalization.CultureInfo.CreateSpecificCulture("en-US") ,"{0:0.00} ", item.Rating)>
                                    </div>
                                </div>
                            </td>
                        }
                        else
                        {
                            <td>
                                @Html.DisplayFor(modelItem => item.Rating)
                            </td>
                        }
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Album.Id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Album.Id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Album.Id })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script src="@Url.Content("~/Scripts/raterater.jquery.js")"></script>
    <script>
        /* Here we initialize raterater on our rating boxes
         */
        $(function () {
            $('.ratebox').raterater({
                submitFunction: '',
                isStatic: true,
                starWidth: 15,
                spaceWidth: 2,
                numStars: 5,
                step: 0.01
            });
        });
    </script>
}

@section css
{
    <link href="@Url.Content("~/Content/raterater.css")" rel="stylesheet" type="text/css">
}

PhotoAlbum/Views/Albums/_CommentsPartial.cshtml
@model IEnumerable<PhotoAlbum.Models.CommentView>
@using Microsoft.AspNet.Identity

@if (Model != null)
{
    foreach (var comment in Model)
    {
        <div class="well well-lg comment-panel" id="comment_@comment.CommentId">
            <div class="row">
                <div class="col-md-6">
                    <span class="glyphicon glyphicon-user"></span><span class="user-name">@comment.UserName</span>
                </div>
                <div class="col-md-6">
                    <div class="text-right">
                        @{ var dateTime = $"{comment.DateTime.ToShortDateString()}  at  {comment.DateTime.ToShortTimeString()}"; }
                        @dateTime
                        @if (User.IsInRole("Admin") || User.Identity.GetUserName() == comment.UserName)
                        {
                            <button id="@comment.CommentId" style="margin-left: 10px" class="delete-comment close" title="Remove this comment"><span class="glyphicon glyphicon-remove text-danger"></span></button>
                        }
                    </div>
                </div>
            </div>
            <hr />
            <div>
                @Html.Raw(comment.Comment)
            </div>
        </div>
    }
}